# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "genawaiter"
version = "0.2.1"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"
license = "MIT"
description = "Stackless generators on stable Rust."
repository = "https://github.com/whatisaphone/genawaiter"
documentation = "https://docs.rs/genawaiter"
readme = "README-crates-io.md"
keywords = ["generator", "yield", "coroutine", "async", "await"]
categories = ["asynchronous", "concurrency", "rust-patterns"]
include = ["Cargo.toml", "README-crates-io.md", "src/**/*.rs"]

[dependencies]

[features]
nightly = []
strict = []
