# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "genawaiter-example-basic"
version = "0.0.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"
license = "MIT"

[workspace]

[dependencies]
genawaiter = { path = "../.." }

[features]
strict = []
